{% set name = "igrafx-mining-sdk" %}
{% set version = "2.34.2" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/igrafx_mining_sdk-{{ version }}.tar.gz
  sha256: 3a4278c04bf8ecf7ff466c9a94e18ceb0634adbbc90fe79d3ed8021a8df4876d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip =24.0.0
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }}
    - requests >=2.30.0,<2.32.0
    - pydruid >=0.6.5,<0.6.7
    - pandas >=2.0.0,<=2.2.1
    - SQLAlchemy >=2.0.29,<2.0.30
    - networkx >=3.0.0,<3.3.0
    - numpy >=1.25.0
    - toml ==0.10.2
    - urllib3 >=2.2.1,<2.2.2
    - python-dotenv ==1.0.1

test:
  source_files:
    - igrafx_mining_sdk/
    - tests/
  imports:
    - igrafx_mining_sdk
    - pytest
  commands:
    - pytest ./tests/test_01_column_mapping.py
    - pip check
  requires:
    - pip =24.0.0
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/igrafx/mining-python-sdk
  license: MIT
  license_file: LICENSE
  summary: "The iGrafx P360 Live Mining SDK is an open source application that can be used to manage your mining projects."
  doc_url: https://github.com/igrafx/mining-python-sdk/blob/dev/README.md
  dev_url: https://github.com/igrafx/mining-python-sdk

extra:
  recipe-maintainers:
    - Dourouve
